pipeline {
  agent any
  environment {
    dockerfile = "./docker/dataverse-k8s/Dockerfile"
    context = "./docker/dataverse-k8s"
    imagetag = "build-${env.BUILD_ID}"
    hublogin = "dockerhub-dataversebot"
    registry = "https://registry.hub.docker.com"
  }
  stages {
    stage('build') {
      steps {
        script {
          docker_image = docker.build("iqss/dataverse-k8s:${env.imagetag}", "--pull -f ${env.dockerfile} ${env.context}")
        }
      }
    }

    stage('push') {
      when {
        anyOf {
          branch 'master'
          tag "v4.*"
        }
      }
      parallel {
        stage('release') {
          when { buildingTag() }
          steps {
            script {
              docker.withRegistry("${env.registry}", "${env.hublogin}") {
                docker_image.push("${env.TAG_NAME}")
              }
            }
          }
        }
        stage('latest') {
          steps {
            script {
              docker.withRegistry("${env.registry}", "${env.hublogin}") {
                docker_image.push("latest")
              }
            }
          }
        }
      }
    }
  }
}
