def k8sVersions = ["1.12.9","1.13.9","1.14.6","1.15.3"]
def tasks = [:]

for(int i=0; i< k8sVersions.size(); i++) {
  def version = k8sVersions[i]
  tasks["K8s v${version}"] = {
    node {
      sh "pwd"
      sh "test/kubeval/kubeval ${version}"
    }
  }
}

stage ("Checkout") {
  checkout scm
}
stage ("KubeVal linting") {
  parallel tasks
}
