void setBuildStatus(String message, String state) {
  step([
      $class: "GitHubCommitStatusSetter",
      reposSource: [$class: "ManuallyEnteredRepositorySource", url: "${env.GIT_URL}"],
      contextSource: [$class: "ManuallyEnteredCommitContextSource", context: "ci/kubeval"],
      errorHandlers: [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
      statusResultSource: [ $class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: message, state: state]] ]
  ]);
}

pipeline {
  agent any
  environment {
    KUBEVAL_DIR = "test/kubeval"
    KUBEVAL_RELEASE= "0.14.0"
  }
  stages {
    stage ("Prepare") {
      steps {
        setBuildStatus("Awaiting KubeVal validation...", "PENDING")
        sh "${KUBEVAL_DIR}/prepare.sh"
      }
    }
    stage ("KubeVal Linting") {
      parallel {
        stage ("1.12.10") {
          environment {
            K8S_RELEASE = "${env.STAGE_NAME}"
          }
          stages {
            stage ("K8s objects") {
              steps {
                sh "${KUBEVAL_DIR}/lint-k8s.sh ${env.K8S_RELEASE}"
              }
            }
            stage ("Kustomize.io") {
              steps {
                sh "${KUBEVAL_DIR}/lint-kustomize.sh ${env.K8S_RELEASE}"
              }
            }
          }
        }
        stage ("1.13.11") {
          environment {
            K8S_RELEASE = "${env.STAGE_NAME}"
          }
          stages {
            stage ("K8s objects") {
              steps {
                sh "${KUBEVAL_DIR}/lint-k8s.sh ${env.K8S_RELEASE}"
              }
            }
            stage ("Kustomize.io") {
              steps {
                sh "${KUBEVAL_DIR}/lint-kustomize.sh ${env.K8S_RELEASE}"
              }
            }
          }
        }
        stage ("1.14.7") {
          environment {
            K8S_RELEASE = "${env.STAGE_NAME}"
          }
          stages {
            stage ("K8s objects") {
              steps {
                sh "${KUBEVAL_DIR}/lint-k8s.sh ${env.K8S_RELEASE}"
              }
            }
            stage ("Kustomize.io") {
              steps {
                sh "${KUBEVAL_DIR}/lint-kustomize.sh ${env.K8S_RELEASE}"
              }
            }
          }
        }
        stage ("1.15.5") {
          environment {
            K8S_RELEASE = "${env.STAGE_NAME}"
          }
          stages {
            stage ("K8s objects") {
              steps {
                sh "${KUBEVAL_DIR}/lint-k8s.sh ${env.K8S_RELEASE}"
              }
            }
            stage ("Kustomize.io") {
              steps {
                sh "${KUBEVAL_DIR}/lint-kustomize.sh ${env.K8S_RELEASE}"
              }
            }
          }
        }
        stage ("1.16.0") {
          environment {
            K8S_RELEASE = "${env.STAGE_NAME}"
          }
          stages {
            stage ("K8s objects") {
              steps {
                sh "${KUBEVAL_DIR}/lint-k8s.sh ${env.K8S_RELEASE}"
              }
            }
            stage ("Kustomize.io") {
              steps {
                sh "${KUBEVAL_DIR}/lint-kustomize.sh ${env.K8S_RELEASE}"
              }
            }
          }
        }
      }
    }
  }
  post {
    success {
        setBuildStatus("KubeVal validation succeeded", "SUCCESS");
    }
    failure {
        setBuildStatus("KubeVal validation failed", "FAILURE");
    }
  }
}
