---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: configure-dataverse-
  labels:
    app.kubernetes.io/name: configure
    app.kubernetes.io/version: "1.1"
    app.kubernetes.io/component: job
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: configure
        app.kubernetes.io/part-of: dataverse
    spec:
      containers:
        - name: configure
          image: iqss/dataverse-k8s
          command: ["scripts/config-job.sh"]
          envFrom:
            - configMapRef:
                name: dataverse
          volumeMounts:
            - name: api-secret
              mountPath: "/secrets/api"
              readOnly: true
            - name: provider-secrets
              mountPath: "/secrets/providers"
              readOnly: true
      initContainers:
        - name: check-dataverse-ready
          image: giantswarm/tiny-tools
          command: ['sh', '-c',
            'until curl -sS -f "http://${DATAVERSE_SERVICE_HOST}:${DATAVERSE_SERVICE_PORT_HTTP}/robots.txt" -m 2 2>&1 > /dev/null;
            do echo waiting for dataverse; sleep 15; done;']
      volumes:
        - name: api-secret
          secret:
            secretName: dataverse-api
        - name: provider-secrets
          secret:
            secretName: dataverse-providers
            optional: true
      restartPolicy: Never
  backoffLimit: 4
